In [1]:
import numpy as np
import pandas as pd
import itertools

In [2]:
import os
path = "New"

Two element matrix generation

In [6]:
two = np.array([[i/100.0, 1.0 - i/100.0] for i in range(1, 100)])
print("Computed shape:", two.shape)

# Remove any duplicates
unique_rows = np.unique(two, axis=0)
print("Unique shape:", unique_rows.shape)
file_path = path +"/matrix_2"
np.save(file_path, unique_rows)
unique_rows

Computed shape: (99, 2)
Unique shape: (99, 2)


array([[0.01, 0.99],
       [0.02, 0.98],
       [0.03, 0.97],
       [0.04, 0.96],
       [0.05, 0.95],
       [0.06, 0.94],
       [0.07, 0.93],
       [0.08, 0.92],
       [0.09, 0.91],
       [0.1 , 0.9 ],
       [0.11, 0.89],
       [0.12, 0.88],
       [0.13, 0.87],
       [0.14, 0.86],
       [0.15, 0.85],
       [0.16, 0.84],
       [0.17, 0.83],
       [0.18, 0.82],
       [0.19, 0.81],
       [0.2 , 0.8 ],
       [0.21, 0.79],
       [0.22, 0.78],
       [0.23, 0.77],
       [0.24, 0.76],
       [0.25, 0.75],
       [0.26, 0.74],
       [0.27, 0.73],
       [0.28, 0.72],
       [0.29, 0.71],
       [0.3 , 0.7 ],
       [0.31, 0.69],
       [0.32, 0.68],
       [0.33, 0.67],
       [0.34, 0.66],
       [0.35, 0.65],
       [0.36, 0.64],
       [0.37, 0.63],
       [0.38, 0.62],
       [0.39, 0.61],
       [0.4 , 0.6 ],
       [0.41, 0.59],
       [0.42, 0.58],
       [0.43, 0.57],
       [0.44, 0.56],
       [0.45, 0.55],
       [0.46, 0.54],
       [0.47, 0.53],
       [0.48,

Three Element Matrix generation

In [8]:
import numpy as np

# Define the constraints
min_value = 0.01
max_value = 0.99
step = 0.01

# Create the array
rows = []
for a in np.arange(min_value, max_value + step, step):
    for b in np.arange(min_value, max_value + step, step):
        c = 1 - a - b
        if min_value <= c <= max_value:
            rows.append([a, b, c])

three = np.array(rows)

print(three)
# print("Number of rows:", len(rows))
print("Computed shape:", three.shape)

# Remove any duplicates
unique_rows = np.unique(three, axis=0)
print("Unique shape:", unique_rows.shape)
file_path = path +"/matrix_3"
np.save(file_path, unique_rows)
unique_rows

[[0.01 0.01 0.98]
 [0.01 0.02 0.97]
 [0.01 0.03 0.96]
 ...
 [0.97 0.01 0.02]
 [0.97 0.02 0.01]
 [0.98 0.01 0.01]]
Computed shape: (4796, 3)
Unique shape: (4796, 3)


array([[0.01, 0.01, 0.98],
       [0.01, 0.02, 0.97],
       [0.01, 0.03, 0.96],
       ...,
       [0.97, 0.01, 0.02],
       [0.97, 0.02, 0.01],
       [0.98, 0.01, 0.01]])

In [9]:
np.unique(unique_rows[:,0])

array([0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 , 0.11,
       0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21, 0.22,
       0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32, 0.33,
       0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43, 0.44,
       0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54, 0.55,
       0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65, 0.66,
       0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77,
       0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88,
       0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98])

Four Element Matrix generation

In [10]:
import numpy as np

# Define the constraints
min_value = 0.01
max_value = 0.99
step = 0.01

# Create the array
rows = []
for a in np.arange(min_value, max_value + step, step):
    for b in np.arange(min_value, max_value + step, step):
        for c in np.arange(min_value, max_value + step, step):
            d = 1 - a - b - c
            if min_value <= d <= max_value:
                rows.append([a, b, c, d])

four = np.array(rows)

print(four)
# print("Number of rows:", len(rows))
print("Computed shape:", four.shape)

# Remove any duplicates
unique_rows = np.unique(four, axis=0)
print("Unique shape:", unique_rows.shape)
file_path = path +"/matrix_4"
np.save(file_path, unique_rows)
unique_rows

[[0.01 0.01 0.01 0.97]
 [0.01 0.01 0.02 0.96]
 [0.01 0.01 0.03 0.95]
 ...
 [0.95 0.02 0.01 0.02]
 [0.96 0.01 0.01 0.02]
 [0.97 0.01 0.01 0.01]]
Computed shape: (153705, 4)
Unique shape: (153705, 4)


array([[0.01, 0.01, 0.01, 0.97],
       [0.01, 0.01, 0.02, 0.96],
       [0.01, 0.01, 0.03, 0.95],
       ...,
       [0.95, 0.02, 0.01, 0.02],
       [0.96, 0.01, 0.01, 0.02],
       [0.97, 0.01, 0.01, 0.01]])

In [11]:
np.unique(unique_rows[:,0])

array([0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 , 0.11,
       0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21, 0.22,
       0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32, 0.33,
       0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43, 0.44,
       0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54, 0.55,
       0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65, 0.66,
       0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77,
       0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88,
       0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97])

Five Element Matrix Generation

In [12]:
import numpy as np

# Define the constraints
min_value = 0.01
max_value = 0.99
step = 0.01

# Create the array
rows = []
for a in np.arange(min_value, max_value + step, step):
    for b in np.arange(min_value, max_value + step, step):
        for c in np.arange(min_value, max_value + step, step):
            for d in np.arange(min_value, max_value + step, step):
                e = 1 - a - b - c - d
                if min_value <= e <= max_value:
                    rows.append([a, b, c, d, e])

five = np.array(rows)

print(five)
# print("Number of rows:", len(rows))
print("Computed shape:", five.shape)

# Remove any duplicates
unique_rows = np.unique(five, axis=0)
print("Unique shape:", unique_rows.shape)
file_path = path +"/matrix_5"
np.save(file_path, unique_rows)
unique_rows

[[0.01 0.01 0.01 0.01 0.96]
 [0.01 0.01 0.01 0.02 0.95]
 [0.01 0.01 0.01 0.03 0.94]
 ...
 [0.94 0.01 0.02 0.01 0.02]
 [0.94 0.02 0.01 0.01 0.02]
 [0.95 0.01 0.01 0.01 0.02]]
Computed shape: (3658030, 5)
Unique shape: (3658030, 5)


array([[0.01, 0.01, 0.01, 0.01, 0.96],
       [0.01, 0.01, 0.01, 0.02, 0.95],
       [0.01, 0.01, 0.01, 0.03, 0.94],
       ...,
       [0.94, 0.01, 0.02, 0.01, 0.02],
       [0.94, 0.02, 0.01, 0.01, 0.02],
       [0.95, 0.01, 0.01, 0.01, 0.02]])

In [13]:
np.unique(unique_rows[:,0])

array([0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 , 0.11,
       0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21, 0.22,
       0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32, 0.33,
       0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43, 0.44,
       0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54, 0.55,
       0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65, 0.66,
       0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77,
       0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88,
       0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95])

Six Element Matrix Generation

In [3]:
# Finding and Saving Combinations
import numpy as np

def find_combinations(start, partial_combination, remaining_numbers, all_combinations):
    if remaining_numbers == 0 and sum(partial_combination) == 1.0:
        all_combinations.append(partial_combination)
        return
    
    if remaining_numbers == 0:
        return

    for i in range(start, 100):
        value = i * 0.01
        find_combinations(i, partial_combination + [value], remaining_numbers - 1, all_combinations)

all_combinations = []
find_combinations(1, [], 6, all_combinations)

# Convert to numpy array and save to a file
all_combinations_np = np.array(all_combinations)
np.save('New/combinations.npy', all_combinations_np)

print("Total combinations:", len(all_combinations))


Total combinations: 141164


In [5]:
loaded_combinations = np.load('New/combinations.npy')

# Remove any duplicates
unique_rows = np.unique(loaded_combinations, axis=0)
print("Unique shape:", unique_rows.shape) # SHape[0] is same after applying unique, so no duplicates found

loaded_combinations[:20]

Unique shape: (141164, 6)


array([[0.01, 0.01, 0.01, 0.01, 0.01, 0.95],
       [0.01, 0.01, 0.01, 0.01, 0.02, 0.94],
       [0.01, 0.01, 0.01, 0.01, 0.03, 0.93],
       [0.01, 0.01, 0.01, 0.01, 0.04, 0.92],
       [0.01, 0.01, 0.01, 0.01, 0.05, 0.91],
       [0.01, 0.01, 0.01, 0.01, 0.06, 0.9 ],
       [0.01, 0.01, 0.01, 0.01, 0.07, 0.89],
       [0.01, 0.01, 0.01, 0.01, 0.08, 0.88],
       [0.01, 0.01, 0.01, 0.01, 0.09, 0.87],
       [0.01, 0.01, 0.01, 0.01, 0.1 , 0.86],
       [0.01, 0.01, 0.01, 0.01, 0.11, 0.85],
       [0.01, 0.01, 0.01, 0.01, 0.12, 0.84],
       [0.01, 0.01, 0.01, 0.01, 0.13, 0.83],
       [0.01, 0.01, 0.01, 0.01, 0.14, 0.82],
       [0.01, 0.01, 0.01, 0.01, 0.15, 0.81],
       [0.01, 0.01, 0.01, 0.01, 0.16, 0.8 ],
       [0.01, 0.01, 0.01, 0.01, 0.17, 0.79],
       [0.01, 0.01, 0.01, 0.01, 0.18, 0.78],
       [0.01, 0.01, 0.01, 0.01, 0.19, 0.77],
       [0.01, 0.01, 0.01, 0.01, 0.2 , 0.76]])

In [6]:
# Loading Combinations and Finding Permutations
from itertools import permutations
import numpy as np

def generate_permutations(all_combinations):
    all_permutations = []
    for combination in all_combinations:
        all_permutations.extend(list(permutations(combination, 6)))
    return np.array(all_permutations)

# Load combinations from the saved file
loaded_combinations = np.load('New/combinations.npy')

all_permutations = generate_permutations(loaded_combinations)

# Print the shape of the array to verify it's correct
# print("Shape of the array:", all_permutations.shape)
# Print the first 10 rows to check if everything is fine
# print(all_permutations[:10])

# Convert the unique_rows set to a NumPy array
six = np.array(list(all_permutations))

print(six)
print("Computed shape:", six.shape)

# Remove any duplicates
unique_rows = np.unique(six, axis=0)
print("Unique shape:", unique_rows.shape)
file_path = path +"/matrix_6"
np.save(file_path, unique_rows)
unique_rows


[[0.01 0.01 0.01 0.01 0.01 0.95]
 [0.01 0.01 0.01 0.01 0.95 0.01]
 [0.01 0.01 0.01 0.01 0.01 0.95]
 ...
 [0.17 0.17 0.17 0.16 0.17 0.16]
 [0.17 0.17 0.17 0.17 0.16 0.16]
 [0.17 0.17 0.17 0.17 0.16 0.16]]
Computed shape: (101638080, 6)
Unique shape: (70560204, 6)


array([[0.01, 0.01, 0.01, 0.01, 0.01, 0.95],
       [0.01, 0.01, 0.01, 0.01, 0.02, 0.94],
       [0.01, 0.01, 0.01, 0.01, 0.03, 0.93],
       ...,
       [0.94, 0.01, 0.02, 0.01, 0.01, 0.01],
       [0.94, 0.02, 0.01, 0.01, 0.01, 0.01],
       [0.95, 0.01, 0.01, 0.01, 0.01, 0.01]])

In [7]:
six = np.load('New/matrix_6.npy')
np.unique(six[:,0])

array([0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 , 0.11,
       0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21, 0.22,
       0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32, 0.33,
       0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43, 0.44,
       0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54, 0.55,
       0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65, 0.66,
       0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77,
       0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88,
       0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95])